"use server";

import { insertExerciseSelections } from "../db/queries";
import type { NewExerciseSelection } from "../db/schema";

export enum ExerciseCategory {
  Compound = "compound",
  Isolation = "isolation",
}

export enum MuscleGroup {
  Chest = "chest",
  Lats = "lats",
  MidUpperBack = "mid_upper_back",
  FrontDelt = "front_delt",
  SideDelt = "side_delt",
  RearDelt = "rear_delt",
  Biceps = "biceps",
  Triceps = "triceps",
  Forearms = "forearms",
  Quad = "quad",
  Hamstring = "hamstring",
  Calf = "calf",
  Glutes = "glutes",
  Core = "core",
}

export enum ExerciseName {
  BarbellBenchPress = "Barbell Bench Press",
  InclineBarbellBenchPress = "Incline Barbell Bench Press",
  DeclineBarbellBenchPress = "Decline Barbell Bench Press",
  DumbbellBenchPress = "Dumbbell Bench Press",
  InclineDumbbellBenchPress = "Incline Dumbbell Bench Press",
  DeclineDumbbellBenchPress = "Decline Dumbbell Bench Press",
  DumbbellFly = "Dumbbell Fly",
  InclineDumbbellFly = "Incline Dumbbell Fly",
  CableFly = "Cable Fly",
  ChestPressMachine = "Chest Press Machine",
  PecDeck = "Pec Deck",
  PushUps = "Push-Ups",
  BarbellRow = "Barbell Row",
  Deadlift = "Deadlift",
  PendlayRow = "Pendlay Row",
  DumbbellRow = "Dumbbell Row",
  SingleArmDumbbellRow = "Single-Arm Dumbbell Row",
  SeatedCableRow = "Seated Cable Row",
  TBarRow = "T-Bar Row",
  MachineRow = "Machine Row",
  DumbbellShrugs = "Dumbbell Shrugs",
  PullUp = "Pull-Up",
  ChinUp = "Chin-Up",
  LatPulldown = "Lat Pulldown",
  LatPrayer = "Lat Prayer",
  OverheadPress = "Overhead Press",
  PushPress = "Push Press",
  DumbbellShoulderPress = "Dumbbell Shoulder Press",
  ArnoldPress = "Arnold Press",
  FrontRaise = "Front Raise",
  ShoulderPressMachine = "Shoulder Press Machine",
  LateralRaise = "Lateral Raise",
  CableLateralRaise = "Cable Lateral Raise",
  RearDeltFly = "Rear Delt Fly",
  FacePull = "Face Pull",
  BarbellSquat = "Barbell Squat",
  FrontSquat = "Front Squat",
  BulgarianSplitSquat = "Bulgarian Split Squat",
  BarbellLunge = "Barbell Lunge",
  LegPress = "Leg Press",
  HackSquat = "Hack Squat",
  LegExtension = "Leg Extension",
  RomanianDeadlift = "Romanian Deadlift",
  LegCurl = "Leg Curl",
  CalfRaise = "Calf Raise",
  SeatedCalfRaise = "Seated Calf Raise",
  BarbellCurl = "Barbell Curl",
  DumbbellCurl = "Dumbbell Curl",
  HammerCurl = "Hammer Curl",
  PreacherCurl = "Preacher Curl",
  CableCurl = "Cable Curl",
  ConcentrationCurl = "Concentration Curl",
  CloseGripBenchPress = "Close-Grip Bench Press",
  Dips = "Dips",
  TricepPushdown = "Tricep Pushdown",
  OverheadTricepExtension = "Overhead Tricep Extension",
  SkullCrusher = "Skull Crusher",
  TricepKickback = "Tricep Kickback",
  Plank = "Plank",
  AbWheelRollout = "Ab Wheel Rollout",
  CableCrunch = "Cable Crunch",
  HangingLegRaise = "Hanging Leg Raise",
}

export async function seedAdditionalExercises() {
  const exercises: NewExerciseSelection[] = [
    { name: ExerciseName.MachineRow, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.MidUpperBack, secondaryMuscleGroup: MuscleGroup.Biceps },
    { name: ExerciseName.DumbbellShrugs, category: ExerciseCategory.Isolation, primaryMuscleGroup: MuscleGroup.MidUpperBack, secondaryMuscleGroup: null },
    { name: ExerciseName.LatPrayer, category: ExerciseCategory.Isolation, primaryMuscleGroup: MuscleGroup.Lats, secondaryMuscleGroup: null },
  ];

  const insertedExercises = await insertExerciseSelections(exercises);
  return insertedExercises;
}

export async function seedExerciseSelections() {
  const exercises: NewExerciseSelection[] = [
    { name: ExerciseName.BarbellBenchPress, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.Chest, secondaryMuscleGroup: MuscleGroup.Triceps },
    { name: ExerciseName.InclineBarbellBenchPress, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.Chest, secondaryMuscleGroup: MuscleGroup.Triceps },
    { name: ExerciseName.DeclineBarbellBenchPress, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.Chest, secondaryMuscleGroup: MuscleGroup.Triceps },
    { name: ExerciseName.DumbbellBenchPress, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.Chest, secondaryMuscleGroup: MuscleGroup.Triceps },
    { name: ExerciseName.InclineDumbbellBenchPress, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.Chest, secondaryMuscleGroup: MuscleGroup.Triceps },
    { name: ExerciseName.DeclineDumbbellBenchPress, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.Chest, secondaryMuscleGroup: MuscleGroup.Triceps },
    { name: ExerciseName.DumbbellFly, category: ExerciseCategory.Isolation, primaryMuscleGroup: MuscleGroup.Chest, secondaryMuscleGroup: null },
    { name: ExerciseName.InclineDumbbellFly, category: ExerciseCategory.Isolation, primaryMuscleGroup: MuscleGroup.Chest, secondaryMuscleGroup: null },
    { name: ExerciseName.CableFly, category: ExerciseCategory.Isolation, primaryMuscleGroup: MuscleGroup.Chest, secondaryMuscleGroup: null },
    { name: ExerciseName.ChestPressMachine, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.Chest, secondaryMuscleGroup: MuscleGroup.Triceps },
    { name: ExerciseName.PecDeck, category: ExerciseCategory.Isolation, primaryMuscleGroup: MuscleGroup.Chest, secondaryMuscleGroup: null },
    { name: ExerciseName.PushUps, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.Chest, secondaryMuscleGroup: MuscleGroup.Triceps },
    { name: ExerciseName.BarbellRow, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.MidUpperBack, secondaryMuscleGroup: MuscleGroup.Biceps },
    { name: ExerciseName.Deadlift, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.MidUpperBack, secondaryMuscleGroup: MuscleGroup.Hamstring },
    { name: ExerciseName.PendlayRow, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.MidUpperBack, secondaryMuscleGroup: MuscleGroup.Biceps },
    { name: ExerciseName.DumbbellRow, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.MidUpperBack, secondaryMuscleGroup: MuscleGroup.Biceps },
    { name: ExerciseName.SingleArmDumbbellRow, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.MidUpperBack, secondaryMuscleGroup: MuscleGroup.Biceps },
    { name: ExerciseName.SeatedCableRow, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.MidUpperBack, secondaryMuscleGroup: MuscleGroup.Biceps },
    { name: ExerciseName.TBarRow, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.MidUpperBack, secondaryMuscleGroup: MuscleGroup.Biceps },
    { name: ExerciseName.PullUp, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.Lats, secondaryMuscleGroup: MuscleGroup.Biceps },
    { name: ExerciseName.ChinUp, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.Lats, secondaryMuscleGroup: MuscleGroup.Biceps },
    { name: ExerciseName.LatPulldown, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.Lats, secondaryMuscleGroup: MuscleGroup.Biceps },
    { name: ExerciseName.FacePull, category: ExerciseCategory.Isolation, primaryMuscleGroup: MuscleGroup.RearDelt, secondaryMuscleGroup: MuscleGroup.MidUpperBack },
    { name: ExerciseName.OverheadPress, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.FrontDelt, secondaryMuscleGroup: MuscleGroup.Triceps },
    { name: ExerciseName.PushPress, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.FrontDelt, secondaryMuscleGroup: MuscleGroup.Triceps },
    { name: ExerciseName.DumbbellShoulderPress, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.FrontDelt, secondaryMuscleGroup: MuscleGroup.Triceps },
    { name: ExerciseName.ArnoldPress, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.FrontDelt, secondaryMuscleGroup: MuscleGroup.Triceps },
    { name: ExerciseName.FrontRaise, category: ExerciseCategory.Isolation, primaryMuscleGroup: MuscleGroup.FrontDelt, secondaryMuscleGroup: null },
    { name: ExerciseName.ShoulderPressMachine, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.FrontDelt, secondaryMuscleGroup: MuscleGroup.Triceps },
    { name: ExerciseName.LateralRaise, category: ExerciseCategory.Isolation, primaryMuscleGroup: MuscleGroup.SideDelt, secondaryMuscleGroup: null },
    { name: ExerciseName.CableLateralRaise, category: ExerciseCategory.Isolation, primaryMuscleGroup: MuscleGroup.SideDelt, secondaryMuscleGroup: null },
    { name: ExerciseName.RearDeltFly, category: ExerciseCategory.Isolation, primaryMuscleGroup: MuscleGroup.RearDelt, secondaryMuscleGroup: null },
    { name: ExerciseName.BarbellSquat, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.Quad, secondaryMuscleGroup: MuscleGroup.Glutes },
    { name: ExerciseName.FrontSquat, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.Quad, secondaryMuscleGroup: MuscleGroup.Core },
    { name: ExerciseName.BulgarianSplitSquat, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.Quad, secondaryMuscleGroup: MuscleGroup.Glutes },
    { name: ExerciseName.BarbellLunge, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.Quad, secondaryMuscleGroup: MuscleGroup.Glutes },
    { name: ExerciseName.LegPress, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.Quad, secondaryMuscleGroup: MuscleGroup.Glutes },
    { name: ExerciseName.HackSquat, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.Quad, secondaryMuscleGroup: MuscleGroup.Glutes },
    { name: ExerciseName.LegExtension, category: ExerciseCategory.Isolation, primaryMuscleGroup: MuscleGroup.Quad, secondaryMuscleGroup: null },
    { name: ExerciseName.RomanianDeadlift, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.Hamstring, secondaryMuscleGroup: MuscleGroup.Glutes },
    { name: ExerciseName.LegCurl, category: ExerciseCategory.Isolation, primaryMuscleGroup: MuscleGroup.Hamstring, secondaryMuscleGroup: null },
    { name: ExerciseName.CalfRaise, category: ExerciseCategory.Isolation, primaryMuscleGroup: MuscleGroup.Calf, secondaryMuscleGroup: null },
    { name: ExerciseName.SeatedCalfRaise, category: ExerciseCategory.Isolation, primaryMuscleGroup: MuscleGroup.Calf, secondaryMuscleGroup: null },
    { name: ExerciseName.BarbellCurl, category: ExerciseCategory.Isolation, primaryMuscleGroup: MuscleGroup.Biceps, secondaryMuscleGroup: null },
    { name: ExerciseName.DumbbellCurl, category: ExerciseCategory.Isolation, primaryMuscleGroup: MuscleGroup.Biceps, secondaryMuscleGroup: null },
    { name: ExerciseName.HammerCurl, category: ExerciseCategory.Isolation, primaryMuscleGroup: MuscleGroup.Biceps, secondaryMuscleGroup: MuscleGroup.Forearms },
    { name: ExerciseName.PreacherCurl, category: ExerciseCategory.Isolation, primaryMuscleGroup: MuscleGroup.Biceps, secondaryMuscleGroup: null },
    { name: ExerciseName.CableCurl, category: ExerciseCategory.Isolation, primaryMuscleGroup: MuscleGroup.Biceps, secondaryMuscleGroup: null },
    { name: ExerciseName.ConcentrationCurl, category: ExerciseCategory.Isolation, primaryMuscleGroup: MuscleGroup.Biceps, secondaryMuscleGroup: null },
    { name: ExerciseName.CloseGripBenchPress, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.Triceps, secondaryMuscleGroup: MuscleGroup.Chest },
    { name: ExerciseName.Dips, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.Triceps, secondaryMuscleGroup: MuscleGroup.Chest },
    { name: ExerciseName.TricepPushdown, category: ExerciseCategory.Isolation, primaryMuscleGroup: MuscleGroup.Triceps, secondaryMuscleGroup: null },
    { name: ExerciseName.OverheadTricepExtension, category: ExerciseCategory.Isolation, primaryMuscleGroup: MuscleGroup.Triceps, secondaryMuscleGroup: null },
    { name: ExerciseName.SkullCrusher, category: ExerciseCategory.Isolation, primaryMuscleGroup: MuscleGroup.Triceps, secondaryMuscleGroup: null },
    { name: ExerciseName.TricepKickback, category: ExerciseCategory.Isolation, primaryMuscleGroup: MuscleGroup.Triceps, secondaryMuscleGroup: null },
    { name: ExerciseName.Plank, category: ExerciseCategory.Isolation, primaryMuscleGroup: MuscleGroup.Core, secondaryMuscleGroup: null },
    { name: ExerciseName.AbWheelRollout, category: ExerciseCategory.Compound, primaryMuscleGroup: MuscleGroup.Core, secondaryMuscleGroup: null },
    { name: ExerciseName.CableCrunch, category: ExerciseCategory.Isolation, primaryMuscleGroup: MuscleGroup.Core, secondaryMuscleGroup: null },
    { name: ExerciseName.HangingLegRaise, category: ExerciseCategory.Isolation, primaryMuscleGroup: MuscleGroup.Core, secondaryMuscleGroup: null },
  ];

  const insertedExercises = await insertExerciseSelections(exercises);
  return insertedExercises;
}
